### ISSUE TITLE
Alert Query

### ISSUE THREAD

**Issue by theadityapathak** [bitnami/bitnami-docker-airflow-exporter#1]
I want to integrate alert manager with it , using postgres db , the best query I can get it , any dags fails is airflow_dag_run_state{state="failed"}>=1 , doesn't fulfill my need , as we already have many fails , is there any other queries we can integrate to achieve whenever a dags fails I get notified on slack.

**Comment by miguelaeh** [comment]
Hi @theadityapathak ,
I not totally sure about what are you trying to achieve, could you provide more information about your use case?

**Comment by theadityapathak** [comment]
I got the solution , anyways thanks for your help @miguelaeh
